In [2]:
#1D indexing and slicing
import numpy as np

a = np.array([10,20,30,40,50])
print(a[0], a[-1]) # first and last
print(a[1:4]) #start at index 1 and stop before index 4
print(a[::2]) #every second element
print(a[::-1]) #descending order


10 50
[20 30 40]
[10 30 50]
[50 40 30 20 10]


In [3]:
b = a[1:4]
b[0] = 999
print(a)                # what happened to a?

[ 10 999  30  40  50]


In [4]:
#2D indexing
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(m[0, 1]) # row 0, column 1 -> 2
print(m[1]) # a whole row -> [4 5 6]
print(m[:, 2]) # a whole column -> [2 5 8]
print(m[:1, 1:]) # top row, last two columns

2
[4 5 6]
[3 6 9]
[[2 3]]


In [ ]:
#Boolean masks, the most important tool for data
scores = np.array([85, 42, 91, 67, 78, 55])

mask = scores >= 60
print(mask) # [ True False  True  True  True False]
print(scores[mask]) # only the True positions
print(scores[scores >= 60]) # the same, in one line
print(mask.sum())
print(mask.mean())
print(np.where(scores >= 80, "high", "normal"))

scores[scores < 60] = 60        # raise every failing score to 60
print(scores)

[ True False  True  True  True False]
[85 91 67 78]
[85 91 67 78]


4
0.6666666666666666
['high' 'normal' 'high' 'normal' 'normal' 'normal']
[85 60 91 67 78 60]


In [22]:
#Reshape and transpose
x = np.arange(12)
print(x.reshape(3, 4))
print(x.reshape(2, -1)) # -1 means "work out this size for me"
print(x.reshape(3, 4).T) #Transpose

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [29]:
#The axis argument
grades = np.array([[85, 90, 78],
                   [70, 65, 80],
                   [92, 88, 95]]) # rows = students, columns = exams
print(grades.mean())
print(grades.mean(axis=0)) # one value per COLUMN (per exam)
print(grades.mean(axis=1)) # one value per ROW (per student)
print("\n")

#Broadcasting
print(grades + 5)

bonus = np.array([1,2,3])
print(grades + bonus)

per_student = np.array([[10], [20], [30]])
print(grades + per_student)

print("\n")
standardize = (grades - grades.mean(axis=0)) / grades.std(axis=0)
print(np.round(standardize, 2))
print(np.round(standardize.mean(axis=0), 2))

82.55555555555556
[82.33333333 81.         84.33333333]
[84.33333333 71.66666667 91.66666667]


[[ 90  95  83]
 [ 75  70  85]
 [ 97  93 100]]
[[86 92 81]
 [71 67 83]
 [93 90 98]]
[[ 95 100  88]
 [ 90  85 100]
 [122 118 125]]


[[ 0.29  0.79 -0.83]
 [-1.34 -1.41 -0.57]
 [ 1.05  0.62  1.41]]
[0. 0. 0.]
