In [35]:
#Create a = np.arange(10, 101, 10). 
# Print the first three elements, the last two, every other element, and the array reversed.
import numpy as np 

a = np.arange(10,101,10)
print(a[:3])
print(a[-2:])
print(a[::2])
print(a[::-1])

[10 20 30]
[ 90 100]
[10 30 50 70 90]
[100  90  80  70  60  50  40  30  20  10]


In [16]:
#Create m = np.arange(1, 17).reshape(4, 4). 
# Print the second column, the bottom-right 2×2 block, and the sum of each row.
m = np.arange(1, 17).reshape(4,4)
print(m)
print("\n")
print(m[:, 1])
print(m.sum(axis=1))
print("\n")
print(m[-2:, -2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


[ 2  6 10 14]
[10 26 42 58]


[[11 12]
 [15 16]]


In [34]:
#With scores = np.array([85, 42, 91, 67, 78, 55, 99, 60]), 
# print the scores 80 or above, how many failed (below 60), and the percentage that passed (60 or above)
scores = np.array([85,42,91, 67, 78, 55, 99, 60])
print(scores[scores >= 80])
print((scores < 60).sum())
print((scores >= 60).mean()*100)

[85 91 99]
2
75.0


In [31]:
#Using the grades matrix from Part 10, 
# print each student's best exam score, and the index of the exam with the highest class average.
grades = np.array([[85, 90, 78],
                   [70, 65, 80],
                   [92, 88, 95]])
print(grades.max(axis=1))
print(grades.mean(axis=0).argmax())

[90 80 95]
2


In [ ]:
#Predict first: what is the shape of np.ones((4, 3)) + np.array([1, 2, 3]), and does it work? 
# Then run it, and try np.ones((4, 3)) + np.array([1, 2]) too.
m = np.ones((4, 3)) + np.array([1,2,3])
print(m)

a = np.ones((4, 3)) + np.array([1, 2])
print(a) #this won't work because the is 4 rows 3 columns but the given array is just missing one more.

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


ValueError: operands could not be broadcast together with shapes (4,3) (2,) 

In [36]:
try:
    print(np.ones((4, 3)) + np.array([1, 2, 3, 4]))     # length 4 = the number of rows
except ValueError as e:
    print("Error:", e)

Error: operands could not be broadcast together with shapes (4,3) (4,) 


In [37]:
print(np.ones((4, 3)) + np.array([[1], [2], [3], [4]]))

[[2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]]
