In [2]:
#1D indexing and slicing
import numpy as np

a = np.array([10,20,30,40,50])
print(a[0], a[-1]) # first and last
print(a[1:4]) #start at index 1 and stop before index 4
print(a[::2]) #every second element
print(a[::-1]) #descending order


10 50
[20 30 40]
[10 30 50]
[50 40 30 20 10]


In [2]:
b = a[1:4]
b[0] = 999
print(a)                # what happened to a?

[ 10 999  30  40  50]


In [4]:
#2D indexing
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(m[0, 1]) # row 0, column 1 -> 2
print(m[1]) # a whole row -> [4 5 6]
print(m[:, 2]) # a whole column -> [2 5 8]
print(m[:1, 1:]) # top row, last two columns

2
[4 5 6]
[3 6 9]
[[2 3]]


In [15]:
#Boolean masks, the most important tool for data
scores = np.array([85, 42, 91, 67, 78, 55])

mask = scores >= 60
print(mask) # [ True False  True  True  True False]
print(scores[mask]) # only the True positions
print(scores[scores >= 60]) # the same, in one line
print(mask.sum())
print(mask.mean())
print(np.where(scores >= 80, "high", "normal"))

scores[scores < 60] = 60        # raise every failing score to 60
print(scores)


[ True False  True  True  True False]
[85 91 67 78]
[85 91 67 78]
4
0.6666666666666666
['high' 'normal' 'high' 'normal' 'normal' 'normal']
[85 60 91 67 78 60]


In [22]:
#Reshape and transpose
x = np.arange(12)
print(x.reshape(3, 4))
print(x.reshape(2, -1)) # -1 means "work out this size for me"
print(x.reshape(3, 4).T) #Transpose

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [29]:
#The axis argument
grades = np.array([[85, 90, 78],
                   [70, 65, 80],
                   [92, 88, 95]]) # rows = students, columns = exams
print(grades.mean())
print(grades.mean(axis=0)) # one value per COLUMN (per exam)
print(grades.mean(axis=1)) # one value per ROW (per student)
print("\n")

#Broadcasting
print(grades + 5)

bonus = np.array([1,2,3])
print(grades + bonus)

per_student = np.array([[10], [20], [30]])
print(grades + per_student)

print("\n")
standardize = (grades - grades.mean(axis=0)) / grades.std(axis=0)
print(np.round(standardize, 2))
print(np.round(standardize.mean(axis=0), 2))

82.55555555555556
[82.33333333 81.         84.33333333]
[84.33333333 71.66666667 91.66666667]


[[ 90  95  83]
 [ 75  70  85]
 [ 97  93 100]]
[[86 92 81]
 [71 67 83]
 [93 90 98]]
[[ 95 100  88]
 [ 90  85 100]
 [122 118 125]]


[[ 0.29  0.79 -0.83]
 [-1.34 -1.41 -0.57]
 [ 1.05  0.62  1.41]]
[0. 0. 0.]


In [19]:
avg = np.array([85.75, 71.75, 81.0, 97.5])
names = np.array(["Aisha", "Bob", "Cy", "Dana", "Eli", "Farah", "Gus", "Hana"])

print(avg.argmax())
print(names[3])
print(avg[3])
avg_sort = np.argsort(avg)[::-1][:3]
#position = np.argsort(avg)[:3]

print(avg_sort)
print((avg > 60).any(axis=0).sum())

3
Dana
97.5
[3 0 2]
1


In [7]:
import numpy as np

scores = np.array([
    [85, 92, 78, 88],
    [70, 65, 80, 72],
    [90, 55, 88, 91],
    [100, 95, 98, 97],
    [55, 62, 48, 60],
    [88, 91, 94, 85],
    [45, 70, 60, 52],
    [76, 80, 82, 79],
])

low = scores <= 60
high = scores >= 90
print(low.shape)
print(low.any(axis=1))
print(int(low.any(axis=0).sum()))
print(low.sum())
print(low.sum(axis=1))
print(low.sum(axis=0))
print(high.any(axis=1).sum())

(8, 4)
[False False  True False  True False  True False]
4
7
[0 0 1 0 3 0 3 0]
[2 1 2 2]
4


In [12]:
import numpy as np

a = np.array([95, 98, 100, 60])

print(a + 5)
print(np.minimum(a + 5, 100))
print(a)

[100 103 105  65]
[100 100 100  65]
[ 95  98 100  60]


In [15]:
avg = np.array([85.75, 71.75, 56.25])
print(np.where(avg >= 50, "A", "Other"))
print(np.where(avg >= 80, "A", np.where(avg >= 70, "B", "F")))

['A' 'A' 'A']
['A' 'B' 'F']


In [18]:
letters = np.array(["A", "B", "A", "F"])
print((letters == "A").sum())

2


In [20]:
m = np.array([[95, 98], [60, 100]])
print(np.minimum(m + 5, 100))  

def first_only(m):
    for row in m:
        return row
print(first_only(m))                

[[100 100]
 [ 65 100]]
[95 98]


In [25]:
import numpy as np
letters = np.array(["A", "B", "A", "F"])
g = "A"

print(letters == "g")
print((letters == g).sum())

[False False False False]
2


In [28]:
scores = np.array([
    [85, 92, 78, 88],
    [70, 65, 80, 72],
    [90, 55, 88, 91],
    [100, 95, 98, 97],
    [55, 62, 48, 60],
    [88, 91, 94, 85],
    [45, 70, 60, 52],
    [76, 80, 82, 79],
])

print(scores.shape)                      # predict: (8, 4)
print(scores.mean(axis=0).shape)         # predict: (4,)
print((scores - scores.mean(axis=0)).shape)   # predict first!
print(scores[:, 0])      # the Quiz column: [ 85  70  90 100  55  88  45  76]
print(scores[:, 3])      # the Final column
print(scores[:, 3] - scores[:, 0])    # Final minus Quiz, one value per student

(8, 4)
(4,)
(8, 4)
[ 85  70  90 100  55  88  45  76]
[88 72 91 97 60 85 52 79]
[ 3  2  1 -3  5 -3  7  3]


In [27]:
col = np.array([10, 20, 30])
print(col.mean(), col.std())             # 20.0 and about 8.16
print((col - col.mean()) / col.std())    # [-1.22  0.    1.22]

20.0 8.16496580927726
[-1.22474487  0.          1.22474487]


In [11]:
import numpy as np
units = np.array([
        [320, 300, 350, 410, 380, 450],
        [150, 170, 160, 200, 210, 190],
        [ 40,  35,  60,  55,  70,  90],
        [ 25,  30,  20,  45,  40,  38],
        [ 60,  55,  80,  75,  95, 110],
        [ 12,  18,  15,  22,  30,  28],
    ])
prices = np.array([1.5, 4.0, 25.0, 18.0, 12.5, 40.0])
products = np.array(["Pen", "Notebook", "Backpack", "Lamp", "Mouse", "Headset"])

totals = units.sum(axis=0)
print(totals)
i = totals.argmax()
print(i)
print(units[i])
print(totals[i])

[607 608 685 807 825 906]
5
[12 18 15 22 30 28]
906


In [4]:
import numpy as np
prices = np.array([1.5, 4.0, 25.0, 18.0, 12.5, 40.0])
print(prices.shape)
col = prices.reshape(-1, 1)
print(col.shape)
print((units * col))
print(units[0] * 1.5)

(6,)
(6, 1)
[[ 480.   450.   525.   615.   570.   675. ]
 [ 600.   680.   640.   800.   840.   760. ]
 [1000.   875.  1500.  1375.  1750.  2250. ]
 [ 450.   540.   360.   810.   720.   684. ]
 [ 750.   687.5 1000.   937.5 1187.5 1375. ]
 [ 480.   720.   600.   880.  1200.  1120. ]]
[480. 450. 525. 615. 570. 675.]


In [3]:
rev = np.array([[10.0, 20.0],
                [30.0, 40.0]])
per_product = rev.sum(axis=1)
print(per_product)                          # [30. 70.]
print(per_product.sum())                    # 100.0, the grand total

[30. 70.]
100.0


In [13]:
low = units < 50
print(low.shape)
print(low)
print(low.sum())
print(low.sum(axis=1))
print(low.any(axis=1))
print(products[low.any(axis=1)])

(6, 6)
[[False False False False False False]
 [False False False False False False]
 [ True  True False False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]
 [ True  True  True  True  True  True]]
14
[0 0 2 6 0 6]
[False False  True  True False  True]
['Backpack' 'Lamp' 'Headset']


In [16]:
low = units < 50
print(low.any(axis=1))
print(low.any(axis=0))

[False False  True  True False  True]
[ True  True  True  True  True  True]


In [17]:
print((units >= 100).all(axis=1))

[ True  True False False False False]


In [1]:
import numpy as np

products = np.array(["Pen", "Notebook", "Backpack", "Lamp", "Mouse", "Headset"])
months = np.array(["Jan", "Feb", "Mar", "Apr", "May", "Jun"])

units = np.array([
    [320, 300, 350, 410, 380, 450],
    [150, 170, 160, 200, 210, 190],
    [ 40,  35,  60,  55,  70,  90],
    [ 25,  30,  20,  45,  40,  38],
    [ 60,  55,  80,  75,  95, 110],
    [ 12,  18,  15,  22,  30,  28],
])
prices = np.array([1.5, 4.0, 25.0, 18.0, 12.5, 40.0])

revenue = units * prices.reshape(-1, 1)
print("revenue shape:", revenue.shape)                 # (6, 6)

# --- tier experiments ---
totals = revenue.sum(axis=1)                            # one total per PRODUCT
print("totals:", totals)                                # [3315. 4320. 8750. 3564. 5937.5 5000.]
print("shape:", totals.shape)                           # (6,)

print(totals >= 6000)                                   # [False False True False False False]
print(np.where(totals >= 6000, "Star", "Other"))
print(np.where(totals >= 6000, "Star",
      np.where(totals >= 4000, "Core", "Niche")))       # the answer, read inside out

# wrong order, to see why the order matters
print(np.where(totals >= 4000, "Core",
      np.where(totals >= 6000, "Star", "Niche")))

revenue shape: (6, 6)
totals: [3315.  4320.  8750.  3564.  5937.5 5000. ]
shape: (6,)
[False False  True False False False]
['Other' 'Other' 'Star' 'Other' 'Other' 'Other']
['Niche' 'Core' 'Star' 'Niche' 'Core' 'Core']
['Niche' 'Core' 'Core' 'Niche' 'Core' 'Core']
