In [ ]:
import numpy as np
#Create temps = np.array([28.5, 31.0, 29.5, 33.0, 30.5]). Print the mean, the max, and the index of the max.
#Convert temps to Fahrenheit (F = C * 9 / 5 + 32) in one line, with no loop.
temp = np.array([28.5, 31.0, 29.5, 33.0, 30.5])
print(temp.mean(), temp.max(), temp.argmax())

F = temp * 9 / 5 + 32
print(F)

30.5 33.0 3
[83.3 87.8 85.1 91.4 86.9]


In [11]:
#Create np.arange(1, 11). Print its squares and the sum of the squares.
arr = np.arange(1,11)
squares = arr ** 2
print(squares)
print(squares.sum())

[  1   4   9  16  25  36  49  64  81 100]
385


In [13]:
#Create a 2×3 array of zeros. Print its shape, ndim, and size.
m = np.zeros([2,3])
print(m.shape)
print(m.ndim)
print(m.size)


(2, 3)
2
6


In [ ]:
#Predict, then run: what do [1, 2, 3] * 2 and 
# np.array([1, 2, 3]) * 2 print? Write one sentence explaining the difference.
arr = np.array([1,2,3]) * 2
print(arr)

print([1,2,3]*2)

#array will compute the math while the one line print will duplicate the array

[2 4 6]
[1, 2, 3, 1, 2, 3]
