In [1]:
import numpy as np

price = ([10,20,30])
print([p * 2 for p in price])

arr = np.array([10,20,30])
print(arr * 2)

print(price * 2)


[20, 40, 60]
[20 40 60]
[10, 20, 30, 10, 20, 30]


In [2]:
#creating arrays and seeded method

a = np.array([1,2,3,4])
print(np.zeros(5))
print(np.ones((2,3)))
print(np.arange(0,10,2))
print(np.linspace(0,1,5))

rng = np.random.default_rng(40)
print(rng.integers(1, 100, size=5))
print(rng.random(3))

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[56 73  3 69 44]
[0.05965206 0.69052097 0.92239752]


In [3]:
#data shapes and array float

m = np.array([[1,2,3], 
             [4,5,6]])
print(m.dtype)
print(m.ndim)
print(m.shape)
print(m.size)

print(np.array([1,2,3.5]))
print(np.array([1,2,3])/2)
print(np.array([1,2,3], dtype=float))

int64
2
(2, 3)
6
[1.  2.  3.5]
[0.5 1.  1.5]
[1. 2. 3.]


In [4]:
#Vectorized math

x = np.array([1,2,3,4,5])
print(x + 10)
print(x * x)
print(x ** 2)
print(np.sqrt(x))
print(x > 2)

a = np.array([1,2,3])
b = np.array([10,20,30])
print(a * b)
print(a + b)

[11 12 13 14 15]
[ 1  4  9 16 25]
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[False False  True  True  True]
[10 40 90]
[11 22 33]


In [5]:
scores = np.array([85,92,78,90])
print(scores.sum(), scores.mean(), scores.max(), scores.min())
print(scores.std())
print(scores.argmax())

345 86.25 92 78
5.402545696243577
1


In [6]:
import time

n = 1_000_000
lst = list(range(n))
arr = np.arange(n)

t0 = time.perf_counter()
doubled_list = [x * 2 for x in lst]
t1 = time.perf_counter()
doubled_arr = arr * 2
t2 = time.perf_counter()

print(f"list : {t1 - t0:.4f}s")
print(f"numpy: {t2 - t1:.4f}s")

list : 0.0681s
numpy: 0.0028s
